import Head from "next/head";
import { Inter } from "@next/font/google";
import RichTextSection from "@/components/RichText/RichTextSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Evaluation App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <RichTextSection />
        </div>
      </main>
    </>
  );
}
